# Generated by Django 5.2.7 on 2025-10-19 12:23

import django.db.models.deletion
import event_view.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EventName', models.CharField(max_length=128)),
                ('PrivateEvent', models.BooleanField(default=True)),
                ('GroupEvent', models.BooleanField(default=False)),
                ('StartDate', models.DateField(default=event_view.models.todays_date)),
                ('EndDate', models.DateField(default=event_view.models.todays_date)),
                ('StartTime', models.TimeField()),
                ('EndTime', models.TimeField()),
                ('Location', models.CharField(blank=True, default='Enter a place')),
                ('Notes', models.TextField(blank=True)),
                ('EventCreatedTime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserEventLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, 'none'), (1, 'owner'), (2, 'invited'), (3, 'accepted'), (4, 'declined')], default=0)),
                ('customUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event_view.event')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('customUser', 'event'), name='unique_customUser_event')],
            },
        ),
    ]
