# Generated by Django 5.2.7 on 2025-10-24 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_view', '0001_initial'),
        ('group_profile', '0004_alter_groupprofile_groupcolour'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='group_profile.groupprofile'),
        ),
    ]
