# Generated by Django 5.2.7 on 2025-10-27 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_view', '0002_event_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='GroupEvent',
        ),
    ]
