# Generated by Django 5.2.7 on 2025-10-16 09:47

import group_profile.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GroupProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GroupName', models.CharField(max_length=128)),
                ('GroupColour', models.CharField(default='FFFFFF', max_length=6)),
                ('DateCreated', models.DateTimeField(auto_now_add=True)),
                ('GroupShareCode', models.CharField(default=group_profile.models.GenerateRandomShareCode, max_length=12)),
            ],
        ),
    ]
