# Generated by Django 5.2.7 on 2025-10-16 11:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_profile', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGroupLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, 'none'), (1, 'Owner'), (2, 'Member')], default=0)),
                ('customUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('groupProfile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='group_profile.groupprofile')),
            ],
        ),
        migrations.AddField(
            model_name='groupprofile',
            name='members',
            field=models.ManyToManyField(through='group_profile.UserGroupLink', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='usergrouplink',
            constraint=models.UniqueConstraint(fields=('customUser', 'groupProfile'), name='unique_customUser_groupProfile'),
        ),
    ]
