# Generated by Django 5.2.7 on 2025-10-17 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_profile', '0002_usergrouplink_groupprofile_members_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupprofile',
            name='GroupName',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
