# Generated by Django 5.2.7 on 2025-10-21 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_profile', '0003_alter_groupprofile_groupname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupprofile',
            name='GroupColour',
            field=models.CharField(default='#FFFFFF', max_length=7),
        ),
    ]
