# Generated by Django 5.2.7 on 2025-10-24 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_profile', '0004_alter_groupprofile_groupcolour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupprofile',
            name='GroupColour',
            field=models.CharField(default='#000000', max_length=7),
        ),
    ]
