# Generated by Django 5.2.7 on 2025-10-29 19:46

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0005_alter_customuser_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='picture',
            field=cloudinary.models.CloudinaryField(blank=True, default='default_profile', max_length=255, verbose_name='image'),
        ),
    ]
